### ISSUE TITLE
Not working with Play 2.4.0

### ISSUE THREAD

**Issue by bwlim** [Rhinofly/play-aws-utils#9]
play-aws-utils 4.1.0 is not compatible with Play 2.4.0

I've got warning messages while building Play 2.4.0 project -----------------------------------------------

[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] * com.typesafe.play:play-ws_2.11:(2.3.0, 2.3.4) -> 2.4.0 (caller: XXXXplay:XXXXplay_2.11:1.0-SNAPSHOT, nl.rhinofly:play-aws-utils_2.11:4.1.0, nl.rhinofly:play-s3_2.11:5.0.2)

And got runtime error -----------------------------------------------

[ERROR] [06/04/2015 17:58:49.841] [application-multimedia-proc-23] [ActorSystem(application)] Uncaught fatal error from thread [application-multimedia-proc-23] shutting down ActorSystem [application]
java.lang.NoSuchMethodError: play.api.libs.ws.WS$.url(Ljava/lang/String;Lplay/api/Application;)Lplay/api/libs/ws/WSRequestHolder;
at fly.play.aws.Aws$AwsRequestBuilder.url(Aws.scala:23)
at fly.play.s3.S3.put(S3.scala:113)
at fly.play.s3.Bucket.add(Bucket.scala:102)
at controllers.NewnalWebImage$$anonfun$uploadFileToS3$1.apply(NewnalWebImage.scala:189)
at controllers.NewnalWebImage$$anonfun$uploadFileToS3$1.apply(NewnalWebImage.scala:187)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Please support Play 2.4.x :D

**Comment by EECOLOR** [comment]
This library will be integrated into 6.0.0 of Play-s3. So it's highly unlikely it will be supporting Play 2.4
